### PR TITLE
#12 Oval hybrids for hybrids MX-Alps footprints

### PR DESCRIPTION
**Pull request by dsanchezseco**
This modded footprints have 1 oval hole for each of the switch pads instead of 2 overlaping pads. This also removes the DRC error from Kicad about overlaping pads/drilled holes being to close.
All the modded footprints' pads have the same dimensions as the original overlapping ones.

They look like this.
Screenshot_20200517_131510

### CODE REVIEW

**Comment by brianmutualaid** [comment]
Thank you for this! Those DRC errors were really bugging me 🙂.

**Comment by WardBenjamin** [comment]
I would like to see a compromise between this and the original version where pin 2 is slotted while pin 1 is not, so that it fixes the drill too close DRC error while still maintaining the positioning benefits of separate holes.

**Comment by dsanchezseco** [comment]
@WardBenjamin the problem with that is that you'll need to connect both holes with traces as is not possible to do it on the footprint. Either that or as it is now  that pops the DRC error

**Comment by WardBenjamin** [comment]
image

@dsanchezseco currently, the DRC error only appears on pin 2, and KiCad correctly recognizes pin 1 as being connected to the second hole (you can see this on the airwire, but I also confirmed on the DRC unconnected report).

**Comment by dsanchezseco** [comment]
Oops forgot about that, it's been a while since I did it

**Comment by WardBenjamin** [comment]
@dsanchezseco I'd be happy to make that change and PR to your fork if you'd like, to include that change in this PR

**Comment by dsanchezseco** [comment]
@WardBenjamin sure, go ahead

**Comment by WardBenjamin** [comment]
@dsanchezseco is it intentional that holes are only present in one of the two mask layers? That seems like an error to me but just wanted to double check.

**Comment by dsanchezseco** [comment]
@WardBenjamin My bad, it was an old version, check now. But i think I changed the silks on this version tho

**Comment by WardBenjamin** [comment]
Looks good, I've got the updates now. I like the silkscreen change as well, good work.

**Comment by dsanchezseco** [comment]
Thanks!

**Comment by WardBenjamin** [comment]
@dsanchezseco to verify: are pads 1/2 the same in _every_ footprint? Right now I'm manually checking the diff but if I can just find and replace in every file it'd be done zippy quick.

**Comment by dsanchezseco** [comment]
@WardBenjamin yes they are, i'd edited all in the text editor, so it should

**Comment by WardBenjamin** [comment]
As per the PR I linked, it would be nice to also have these footprints in the KiCad standard library for reuse instead of having them scattered across various Github repositories (to reduce confusion and reduce the barrier to entry). I am willing to help out with this.

**Comment by gimbas** [comment]
I'm working on it, or at least I'm planing to @WardBenjamin

**Comment by perigoso** [comment]
I'm starting an effort to merge the library to the official libraries, am including these changes. #11

**Comment by ai03-2725** [comment]
Apologize for the ridiculous delay; finally got around to checking pending PRs after too long.  
I will have to decline this PR, for the holes were purposely split apart into two rather than oval based on past experiences with similar footprints and the reduced chance of user assembly error when using the split hole design.  
If the footprints are supplied as an entirely separate collection (i.e. MX_Alps_Hybrid_Ovals.pretty subfolder), it might be worthwhile since it allows for the option for using such footprints if desired without breaking changes on numerous existing PCB projects.

**Comment by dsanchezseco** [comment]
Sorry for the delay from my side(hahahaha), yeah, it totally makes sense. Now that I assembled one pcb without plate I understand why there was two holes.

Thanks for the awesome work!

**Pull request closed without merging**
